# Generated by Django 5.1.6 on 2025-04-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_quantity_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
